--- 
abstract: like PodWeaver, but more erratic and amateurish
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: Dist-Zilla-Plugin-PodPurler
requires: 
  Dist::Zilla: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Autobox: 0.08
  PPI: 0
  Pod::Eventual: 0
version: 0.001
